name: vertx-redis-client (4.x)
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: true
        default: "4.x"
        description: Set the branch to test

jobs:
  CI:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            jdk: 8
          - os: ubuntu-latest
            jdk: 17
    uses: ./.github/workflows/ci.yml
    with:
      branch: ${{ inputs.branch }}
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
    secrets: inherit
